package com.drumbeatrepo.sequencer

enum MidiDrumType(val midiNote: Int):
  case ACOUSTIC_BASS_DRUM extends MidiDrumType(35)
  case BASS_DRUM_1 extends MidiDrumType(36)
  case SIDE_STICK extends MidiDrumType(37)
  case ACOUSTIC_SNARE extends MidiDrumType(38)
  case HAND_CLAP extends MidiDrumType(39)
  case ELECTRIC_SNARE extends MidiDrumType(40)
  case LOW_FLOOR_TOM extends MidiDrumType(41)
  case CLOSED_HI_HAT extends MidiDrumType(42)
  case HIGH_FLOOR_TOM extends MidiDrumType(43)
  case PEDAL_HI_HAT extends MidiDrumType(44)
  case LOW_TOM extends MidiDrumType(45)
  case OPEN_HI_HAT extends MidiDrumType(46)
  case LOW_MID_TOM extends MidiDrumType(47)
  case HI_MID_TOM extends MidiDrumType(48)
  case CRASH_CYMBAL_1 extends MidiDrumType(49)
  case HIGH_TOM extends MidiDrumType(50)
  case RIDE_CYMBAL_1 extends MidiDrumType(51)
  case CHINESE_CYMBAL extends MidiDrumType(52)
  case RIDE_BELL extends MidiDrumType(53)
  case TAMBOURINE extends MidiDrumType(54)
  case SPLASH_CYMBAL extends MidiDrumType(55)
  case COWBELL extends MidiDrumType(56)
  case CRASH_CYMBAL_2 extends MidiDrumType(57)
  case VIBRASLAP extends MidiDrumType(58)
  case RIDE_CYMBAL_2 extends MidiDrumType(59)
  case HI_BONGO extends MidiDrumType(60)
  case LOW_BONGO extends MidiDrumType(61)
  case MUTE_HI_CONGA extends MidiDrumType(62)
  case OPEN_HI_CONGA extends MidiDrumType(63)
  case LOW_CONGA extends MidiDrumType(64)
  case HIGH_TIMBALE extends MidiDrumType(65)
  case LOW_TIMBALE extends MidiDrumType(66)
  case HIGH_AGOGO extends MidiDrumType(67)
  case LOW_AGOGO extends MidiDrumType(68)
  case CABASA extends MidiDrumType(69)
  case MARACAS extends MidiDrumType(70)
  case SHORT_WHISTLE extends MidiDrumType(71)
  case LONG_WHISTLE extends MidiDrumType(72)
  case SHORT_GUIRO extends MidiDrumType(73)
  case LONG_GUIRO extends MidiDrumType(74)
  case CLAVES extends MidiDrumType(75)
  case HI_WOOD_BLOCK extends MidiDrumType(76)
  case LOW_WOOD_BLOCK extends MidiDrumType(77)
  case MUTE_CUICA extends MidiDrumType(78)
  case OPEN_CUICA extends MidiDrumType(79)
  case MUTE_TRIANGLE extends MidiDrumType(80)
  case OPEN_TRIANGLE extends MidiDrumType(81)

object MidiDrumType:
  private val byMidiNote = values.map(d => d.midiNote -> d).toMap

  def fromMidiNote(note: Int): Option[MidiDrumType] =
    byMidiNote.get(note)
