services:
  # Backend Application Service
  - type: web
    name: drum-beat-repo-app
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    runtime: docker
    envVars:
      - key: DATABASE_CONNECTION_STRING
        value: mongodb://admin:pass@mongo-db-service:27017