services:
  # Backend Application Service
  - type: web
    name: drum-beat-repo-app
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_CONNECTION_STRING
        value: mongodb://admin:pass@mongo-db-service:27017