name: ScalaTest
description: Build and test scala and upload

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup Java 25 (Temurin)
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1

    - name: Test Scala
      run: sbt coverage testFull coverageReport
      working-directory: engine
      shell: bash

    - name: Build Scala.js
      run: sbt fastLinkJS
      working-directory: engine
      shell: bash

    - name: Post-process Scala.js output
      run: echo 'globalThis.SequencerEngine = SequencerEngine;' >> ../frontend/engine/main.js
      working-directory: engine
      shell: bash

    - name: Upload Scala.js artifact
      uses: actions/upload-artifact@v7
      with:
        name: scalajs-artifact
        path: frontend/engine/
        if-no-files-found: error