export enum MidiDrumType {
  ACOUSTIC_BASS_DRUM = 35,
  BASS_DRUM_1 = 36,
  SIDE_STICK = 37,
  ACOUSTIC_SNARE = 38,
  HAND_CLAP = 39,
  ELECTRIC_SNARE = 40,
  LOW_FLOOR_TOM = 41,
  CLOSED_HI_HAT = 42,
  HIGH_FLOOR_TOM = 43,
  PEDAL_HI_HAT = 44,
  LOW_TOM = 45,
  OPEN_HI_HAT = 46,
  LOW_MID_TOM = 47,
  HI_MID_TOM = 48,
  CRASH_CYMBAL_1 = 49,
  HIGH_TOM = 50,
  RIDE_CYMBAL_1 = 51,
  CHINESE_CYMBAL = 52,
  RIDE_BELL = 53,
  TAMBOURINE = 54,
  SPLASH_CYMBAL = 55,
  COWBELL = 56,
  CRASH_CYMBAL_2 = 57,
  VIBRASLAP = 58,
  RIDE_CYMBAL_2 = 59,
  HI_BONGO = 60,
  LOW_BONGO = 61,
  MUTE_HI_CONGA = 62,
  OPEN_HI_CONGA = 63,
  LOW_CONGA = 64,
  HIGH_TIMBALE = 65,
  LOW_TIMBALE = 66,
  HIGH_AGOGO = 67,
  LOW_AGOGO = 68,
  CABASA = 69,
  MARACAS = 70,
  SHORT_WHISTLE = 71,
  LONG_WHISTLE = 72,
  SHORT_GUIRO = 73,
  LONG_GUIRO = 74,
  CLAVES = 75,
  HI_WOOD_BLOCK = 76,
  LOW_WOOD_BLOCK = 77,
  MUTE_CUICA = 78,
  OPEN_CUICA = 79,
  MUTE_TRIANGLE = 80,
  OPEN_TRIANGLE = 81
}

export const MidiDrumNames: Record<MidiDrumType, string> = {
  [MidiDrumType.ACOUSTIC_BASS_DRUM]: "Acoustic Bass Drum",
  [MidiDrumType.BASS_DRUM_1]: "Bass Drum 1",
  [MidiDrumType.SIDE_STICK]: "Side Stick",
  [MidiDrumType.ACOUSTIC_SNARE]: "Acoustic Snare",
  [MidiDrumType.HAND_CLAP]: "Hand Clap",
  [MidiDrumType.ELECTRIC_SNARE]: "Electric Snare",
  [MidiDrumType.LOW_FLOOR_TOM]: "Low Floor Tom",
  [MidiDrumType.CLOSED_HI_HAT]: "Closed Hi-Hat",
  [MidiDrumType.HIGH_FLOOR_TOM]: "High Floor Tom",
  [MidiDrumType.PEDAL_HI_HAT]: "Pedal Hi-Hat",
  [MidiDrumType.LOW_TOM]: "Low Tom",
  [MidiDrumType.OPEN_HI_HAT]: "Open Hi-Hat",
  [MidiDrumType.LOW_MID_TOM]: "Low-Mid Tom",
  [MidiDrumType.HI_MID_TOM]: "Hi-Mid Tom",
  [MidiDrumType.CRASH_CYMBAL_1]: "Crash Cymbal 1",
  [MidiDrumType.HIGH_TOM]: "High Tom",
  [MidiDrumType.RIDE_CYMBAL_1]: "Ride Cymbal 1",
  [MidiDrumType.CHINESE_CYMBAL]: "Chinese Cymbal",
  [MidiDrumType.RIDE_BELL]: "Ride Bell",
  [MidiDrumType.TAMBOURINE]: "Tambourine",
  [MidiDrumType.SPLASH_CYMBAL]: "Splash Cymbal",
  [MidiDrumType.COWBELL]: "Cowbell",
  [MidiDrumType.CRASH_CYMBAL_2]: "Crash Cymbal 2",
  [MidiDrumType.VIBRASLAP]: "Vibraslap",
  [MidiDrumType.RIDE_CYMBAL_2]: "Ride Cymbal 2",
  [MidiDrumType.HI_BONGO]: "Hi Bongo",
  [MidiDrumType.LOW_BONGO]: "Low Bongo",
  [MidiDrumType.MUTE_HI_CONGA]: "Mute Hi Conga",
  [MidiDrumType.OPEN_HI_CONGA]: "Open Hi Conga",
  [MidiDrumType.LOW_CONGA]: "Low Conga",
  [MidiDrumType.HIGH_TIMBALE]: "High Timbale",
  [MidiDrumType.LOW_TIMBALE]: "Low Timbale",
  [MidiDrumType.HIGH_AGOGO]: "High Agogo",
  [MidiDrumType.LOW_AGOGO]: "Low Agogo",
  [MidiDrumType.CABASA]: "Cabasa",
  [MidiDrumType.MARACAS]: "Maracas",
  [MidiDrumType.SHORT_WHISTLE]: "Short Whistle",
  [MidiDrumType.LONG_WHISTLE]: "Long Whistle",
  [MidiDrumType.SHORT_GUIRO]: "Short Guiro",
  [MidiDrumType.LONG_GUIRO]: "Long Guiro",
  [MidiDrumType.CLAVES]: "Claves",
  [MidiDrumType.HI_WOOD_BLOCK]: "Hi Wood Block",
  [MidiDrumType.LOW_WOOD_BLOCK]: "Low Wood Block",
  [MidiDrumType.MUTE_CUICA]: "Mute Cuica",
  [MidiDrumType.OPEN_CUICA]: "Open Cuica",
  [MidiDrumType.MUTE_TRIANGLE]: "Mute Triangle",
  [MidiDrumType.OPEN_TRIANGLE]: "Open Triangle"
};
