name: Deploy Angular App to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main # Adjust this to your default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Test
        uses: ./.github/actions/test/
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

      - name: Copy CNAME file
        run: |
          echo "www.drumbeatrepo.com" > dist/browser/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/browser/