name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    defaults:
      run:
        working-directory: ./frontend

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.GHPAGES }}
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        deploy_branch: gh-pages # The branch the action should deploy to.
        base_href: '' # empty
        angular_dist_build_folder: dist/drum-beat-repo # The folder where your project is supposed to be after running ng build by the action.

permissions:
  contents: write # Allow write permission to GITHUB_TOKEN to commit to deploy branch.
