name: Tests

on:
  pull_request:
    branches: [ "main" ]
    paths: [ 'frontend/**', 'engine/**', '.github/**' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Validate Scala
        uses: ./.github/actions/scala-test/

      - name: Upload Scala coverage to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}

      - name: Validate Angular
        uses: ./.github/actions/angular-test/
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
