name: Tests

on:
  pull_request:
    branches: [ "main" ]
    paths: [ 'frontend/**', '.github/**' ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate
        uses: ./.github/actions/angular-test/
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
